version: "1"
services:
  shiny:
    container_name: shiny-wine-app
    depends_on:
      - postgres
    environment:
      DISABLE_AUTH: "true"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    build: ./shiny
    ports:
      - "3838:3838"
    volumes:
      - type: bind
        source: ./shiny/shiny-wine/app.R
        target: /home/app/app.R
      - type: bind
        source: ./shiny/shiny-wine/db.R
        target: /home/app/db.R
  postgres:
    container_name: shiny-wine-db
    build: ./postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATA: "/data/shiny_wine_db"
    volumes:
      - db:/data/shiny_wine_db
    restart: unless-stopped
volumes:
  db:
    external: true
